# Generated by Django 5.0 on 2024-04-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0006_debitnote_comments_debitnote_history_debitnote_item_and_more'),
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendorcredit',
            new_name='debitnote',
        ),
    ]
